export {TxtFileIcon} from './txt-file-icon'
export {ZipFileIcon} from './zip-file-icon'
export {PdfFileIcon } from './pdf-file-icon'
export {MailFileIcon} from './mail-file-icon'
export  {PptxFileIcon} from './pptx-file-icon'
export {ExcelFileIcon} from './excel-file-icon'
export {VisioFileIcon } from './visio-file-icon'
export {WordFileIcon    } from './word-file-icon'
export {OutlookFileIcon} from './outlook-file-icon'